### ISSUE TITLE
跟楼主确认几个问题，辛苦看到后帮忙解答下，多谢

### ISSUE THREAD

**Issue by xoyabc** [anpengapple/doubanbooks#1]
1.楼主用的版本是2.7还是3.x呢。
2.我运行脚本时一直提示以下报错，请问楼主用的是自带的urllib模块还是requests模块？
`Traceback (most recent call last):
  File "douban_books.py", line 9, in <module>
    from urllib import request
ImportError: cannot import name request`

**Comment by anpengapple** [comment]
> 1.楼主用的版本是2.7还是3.x呢。
> 2.我运行脚本时一直提示以下报错，请问楼主用的是自带的urllib模块还是requests模块？
> Traceback (most recent call last): File "douban_books.py", line 9, in <module> from urllib import request ImportError: cannot import name request

1、我用的是python3
2、我用的是urllib模块，这里引入模块你可以试试用  import urllib.request
如果用requests模块，应该会更方便一些
@xoyabc

**Comment by xoyabc** [comment]
@anpengapple 
感谢回复，我稍后再试一下，要是有问题再向你请教。

**Comment by xoyabc** [comment]
1.执行时给出以下提示，见图1
2.douban.csv里面只有首行标题，没有内容，见图2
3.辛苦楼主有空再给看一下是否是豆瓣接口限制还是别的问题，感谢。

图1：
![1](https://user-images.githubusercontent.com/7418915/27492854-3dc9e6f6-587a-11e7-9369-a27655bfe6e1.jpg)
图2：
![2](https://user-images.githubusercontent.com/7418915/27492954-a77ab968-587a-11e7-97eb-6b6f64e4d4b2.jpg)

**Comment by anpengapple** [comment]
看起来是正则匹配书的时候没有找到。这个有可能是因为你搜的书没有搜到，或者评分人数太少（少于10人评价时豆瓣没有评分），或者爬的次数多了豆瓣把你的ip暂时封了。貌似12小时后解封。
这段代码配套的博客地址：http://www.cnblogs.com/anpengapple/p/6062833.html
对这个错误没有解释，但是你后面也许能用到。
@xoyabc
